### ISSUE TITLE
Guild Wars 2 login error (Arenanet, Europe)

### ISSUE THREAD

**Issue by gr0ebi** [uklans/cache-domains#104]
### Describe the issue you are having
arenanet cache domains are caching but login to Guild Wars 2 isn't possible - Error 58

### Describe your setup?
lancachenet/monolithic (docker) with Unbound Server with uklans/cache-domains git

lancachenet/monolithic: 10.0.0.200:80
lancachenet/sniproxy: 10.0.0.200:443

### Are you running sniproxy
Yes, also docker

### DNS Configuration
```
server:
  local-zone: "assetcdn.101.arenanetworks.com" redirect
  local-data: "assetcdn.101.arenanetworks.com 30 IN A 10.0.0.200"
  local-zone: "assetcdn.102.arenanetworks.com" redirect
  local-data: "assetcdn.102.arenanetworks.com 30 IN A 10.0.0.200"
  local-zone: "assetcdn.103.arenanetworks.com" redirect
  local-data: "assetcdn.103.arenanetworks.com 30 IN A 10.0.0.200"
  local-zone: "live.patcher.bladeandsoul.com" redirect
  local-data: "live.patcher.bladeandsoul.com 30 IN A 10.0.0.200"

```

### Sniproxy output
No output from sniproxy that is arenanet related
