### ISSUE TITLE
Pihole won't start because *.hosts are placed in the "/etc/dnsmasq.d" directory

### ISSUE THREAD

**Issue by DragonQ** [uklans/cache-domains#155]
### Describe the issue you are having
*.hosts files should not be placed in the `/etc/dnsmasq.d` directory, because dnsmasq interprets anything in that directory as a configuration file. I don't know if this breaks _lancachenet/lancache-dns_ but it does break pihole, which crashes on startup when dnsmasq fails to parse those files.

The solution is to instead place the *.hosts files into `/etc/dnsmasq.hosts` (or whatever) instead. Half of this solution is contained in [this commit](https://github.com/DragonQ/cache-domains/commit/3e155a7afc883de4caafd3c9cc54d12c69eae9dd), which makes `create-dnsmasq.sh` change the location of the *hosts files written in the config files. The other half of the solution is to ensure the *.hosts files are actually located in that new directory. I use a script to do this:

```
./create-dnsmasq.sh
sudo cp -rf ./output/dnsmasq/*.conf ${DNSMASQ_DIR}
sudo cp -rf ./output/dnsmasq/*.hosts ${HOSTS_DIR}
```

I am unsure what changes would be needed to ensure compatibility with _lancachenet/lancache-dns_, however. Presumably they have some kind of script that pulls the files from the `output` directory to wherever they need to be, in which case that would need updating to match.

### Describe your setup?
I have a pihole container with its dnsmasq directories populated with the files generated by the `cache-domains` script. This ensures any compatible game servers are redirected to the lancache/monolithic container, and all other traffic is routed to a cloudflared container.

### Are you running sniproxy
Yes

### DNS Configuration
I use this docker-compose script for pi-hole, lancache, and DNSSEC:

```
version: '3.7'
services:
    lancache-monolithic:
        container_name: lancache
        image: 'lancachenet/monolithic:latest'
        restart: unless-stopped
        networks:
            pihole-net:
                ipv4_address: ${LANCACHE_IP}
        volumes:
            - '/data/cache:/data/cache'
            - '/data/logs:/data/logs'
        ports:
            - '${HOST_IP}:80:80'
        environment:
            - UPSTREAM_DNS=${DNS_SERVERS}
            - CACHE_MEM_SIZE=${CACHE_MEM_SIZE}
            - CACHE_DISK_SIZE=${CACHE_DISK_SIZE}
            - CACHE_DOMAINS_REPO=${CACHE_DOMAINS_REPO}
            - CACHE_DOMAINS_BRANCH=${CACHE_DOMAINS_BRANCH}
    sniproxy:
        container_name: lancache-sniproxy
        image: 'lancachenet/sniproxy:latest'
        restart: unless-stopped
        networks:
            pihole-net:
                ipv4_address: ${SNIPROXY_IP}
        ports:
            - '${HOST_IP}:443:443'
        environment:
            - UPSTREAM_DNS=${DNS_SERVERS_SNI}
    pihole:
        container_name: pihole
        image: 'pihole/pihole:latest'
        restart: unless-stopped
        networks:
            pihole-net:
                ipv4_address: ${PIHOLE_IP}
        volumes:
            - ${PIHOLE_ROOT_PATH}/etc/:/etc/pihole/
            - ${PIHOLE_ROOT_PATH}/dnsmasq.d/:/etc/dnsmasq.d/
            - ${PIHOLE_ROOT_PATH}/dnsmasq.hosts/:/etc/dnsmasq.hosts/
        ports:
            - '${HOST_IP}:53:53/tcp'
            - '${HOST_IP}:53:53/udp'
            - '${HOST_IP}:8080:80/tcp'
        environment:
            - TZ='Europe/London'
            - WEBPASSWORD=${WEB_PASSWORD}
            - DNS1=${CLOUDFLARED_DNS_IP}
            - DNS2=no
        dns:
            - 127.0.0.1
            - 1.1.1.1
    cloudflared:
        container_name: cloudflared
        image: 'crazymax/cloudflared:latest'
        restart: unless-stopped
        networks:
            pihole-net:
                ipv4_address: ${CLOUDFLARED_IP}
        ports:
            #- '${HOST_IP}:53:5053/udp'
            - '${HOST_IP}:49312:49312/tcp'
        environment:
            - "TZ=Europe/London"
            - "TUNNEL_DNS_UPSTREAM=${UPSTREAM_DNS_SERVERS}"
    ouroboros:
        container_name: ouroboros
        hostname: ouroboros
        image: pyouroboros/ouroboros
        restart: unless-stopped
        networks:
            pihole-net:
                ipv4_address: ${OUROBOROS_IP}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - CLEANUP=true
            - INTERVAL=86400
            - CRON="5 1 * * *"
            - LOG_LEVEL=info
            - SELF_UPDATE=true
            - IGNORE="mongo influxdb postgres mariadb"
            - TZ=Europe/London

networks:
  pihole-net:
    ipam:
      config:
        - subnet: ${IP_SUBNET}
```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
      1 cdn1.unrealengine.com
      1 cdn2.unrealengine.com
      1 cm2-ams1.cm.steampowered.com
      1 cm3-lhr1.cm.steampowered.com
      5 cp601.prod.do.dsp.mp.microsoft.com
      3 geo.prod.do.dsp.mp.microsoft.com
      3 kv601.prod.do.dsp.mp.microsoft.com
      7 nydus.battle.net
      1 static8.cdn.ubi.com
     10 steamcdn-a.akamaihd.net
      1 ubiservices.cdn.ubi.com
```
