### ISSUE TITLE
Generation of unbound rules creates invalid entries due to multiple empty lines in steam.txt, xboxlive.txt and twitch.txt

### ISSUE THREAD

**Issue by systemofapwne** [uklans/cache-domains#157]
### Describe the issue you are having
Generation of unbound rules creates invalid entries due to multiple empty lines in steam.txt, xboxlive.txt and twitch.txt

### Describe your setup?
Not of importance here

### Are you running sniproxy
Not of importance here

### DNS Configuration
Not of importance here

### Sniproxy output
Not of importance here

**Way to reproduce:**
Checkout 019ec04f270e0b0d7b85dfb3d62ab1bfeb5d9d19 and add a  scripts/config.json with the following content to the repo
```
{
	"ips": {
		"default":		["1.2.3.4"]
	},
	"cache_domains": {
		"steam": 		"default",
		"twitch": 		"default",
		"xboxlive": 	"default"
	}
}
```

Now run scripts/create.unbound.sh

The content of the generated files now have an invalid entry at the beginning which will prevent unbound from starting

```
server:
  local-zone: "" redirect
  local-data: " 30 IN A 1.2.3.4"
  local-zone: "lancache.steamcontent.com" redirect
  local-data: "lancache.steamcontent.com 30 IN A 1.2.3.4"
```

```
server:
  local-zone: "" redirect
  local-data: " 30 IN A 1.2.3.4"
```

```
server:
  local-zone: "" redirect
  local-data: " 30 IN A 1.2.3.4"
  local-zone: "assets1.xboxlive.com" redirect
  local-data: "assets1.xboxlive.com 30 IN A 1.2.3.4"
  local-zone: "assets1.xboxlive.com.nsatc.net" redirect
  local-data: "assets1.xboxlive.com.nsatc.net 30 IN A 1.2.3.4"
  local-zone: "assets2.xboxlive.com" redirect
  local-data: "assets2.xboxlive.com 30 IN A 1.2.3.4"
  local-zone: "d1.xboxlive.com" redirect
  local-data: "d1.xboxlive.com 30 IN A 1.2.3.4"
  local-zone: "dlassets.xboxlive.com" redirect
  local-data: "dlassets.xboxlive.com 30 IN A 1.2.3.4"
  local-zone: "xbox-mbr.xboxlive.com" redirect
  local-data: "xbox-mbr.xboxlive.com 30 IN A 1.2.3.4"
  local-zone: "xboxone.loris.llnwd.net" redirect
  local-data: "xboxone.loris.llnwd.net 30 IN A 1.2.3.4"
  local-zone: "xboxone.loris.llnwd.net" redirect
  local-data: "xboxone.loris.llnwd.net 30 IN A 1.2.3.4"
  local-zone: "xboxone.vo.llnwd.net" redirect
  local-data: "xboxone.vo.llnwd.net 30 IN A 1.2.3.4"
  local-zone: "xvcf1.xboxlive.com" redirect
  local-data: "xvcf1.xboxlive.com 30 IN A 1.2.3.4"
```

This behaviour can be mitigated by removing the (multiple) empty lines in steam.txt, twitch.txt and xboxlive.txt. While having one empty line at the end of steam.txt and xboxlive.txt seems to be ok, having two will make the script fail.

A totally empty file (twitch.txt for example) will nontheless create these invalid entries.

The fix would be to check for empty lines in scripts/create-unbound.sh and ignoring them.

**Edit**
Added a PR to address this issue: https://github.com/uklans/cache-domains/pull/158
